# title: "CS Notes"
# Set a path/url to a logo that will be displayed instead of the title
logo: "_assets/images/avatar.png"
# Color scheme currently only supports "dark" or nil (default)
color_scheme: light
search_enabled: true
theme: jekyll-theme-minimal
