# title: "CS Notes"
# Set a path/url to a logo that will be displayed instead of the title
logo: "/_assets/images/avatar.png"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true
