#title: "My Docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/avatar.png"

# Enable or disable the site search
search_enabled: true

